### ISSUE TITLE
mdrpc doesn't work with certain streams that only have an icy-title and nothing else.

### ISSUE THREAD

**Issue by Gogo268** [modeco80/mdrpc#3]
OS: debian bookworm/sid x86_64
mpv version: 0.34.1

it does hook onto my discord client and displays my username, but afterwards constantly outputs this error message until i quit mpv.

radio used (that has only icy-title): [http://radio.modules.pl:8500/](url)

screenshot of what happens:
![image](https://user-images.githubusercontent.com/37984199/155805750-ffc7f843-f027-4c04-ab7c-96ee1c7c0cd8.png)

**Comment by Gogo268** [comment]
can't reproduce issue with another stream that also has only an icy-title [http://scenestream.net:8000/nectarine](url), however title itself doesn't display only the stream name does.

![image](https://user-images.githubusercontent.com/37984199/155806943-f0ff2dd2-dbb6-4a28-9755-6876d3ff3e2d.png)

**Comment by modeco80** [comment]
hm.
I honestly probably need to completely rewrite this thing for a multitude of reasons (several of them being my poor wrapping of mpv apis, although no one's really made an alternative API wrapper for C++ so :woman_shrugging:)

I'd also like to maybe be able to use upstream rpc/GameSDK, or better yet, completely remove the need for vendoring by writing my own async client library (as I really do *NOT* like the forced inclusion of rapidjson), as that seems more stable then pinning to a version of the rpc SDK which I've hacked to use `std::function<R(Args...)>` instead of bare function pointers.
